// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.5
// source: kvstore.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_PUT      OperationType = 0
	OperationType_GET      OperationType = 1
	OperationType_DELETE   OperationType = 3
	OperationType_BATCHPUT OperationType = 4
	OperationType_SCAN     OperationType = 5
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "PUT",
		1: "GET",
		3: "DELETE",
		4: "BATCHPUT",
		5: "SCAN",
	}
	OperationType_value = map[string]int32{
		"PUT":      0,
		"GET":      1,
		"DELETE":   3,
		"BATCHPUT": 4,
		"SCAN":     5,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_kvstore_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_kvstore_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{0}
}

// PutRequest defines the request structure for Put
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// PutResponse defines the response structure for Put
type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Updated       bool                   `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Added         bool                   `protobuf:"varint,3,opt,name=added,proto3" json:"added,omitempty"`
	Old           []byte                 `protobuf:"bytes,4,opt,name=old,proto3" json:"old,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PutResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *PutResponse) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

func (x *PutResponse) GetOld() []byte {
	if x != nil {
		return x.Old
	}
	return nil
}

// GetRequest defines the request structure for Get
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// GetResponse defines the response structure for Get
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"` // indicates whether the key was found
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// DeleteRequest defines the request structure for Delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// DeleteResponse defines the response structure for Delete
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Old           []byte                 `protobuf:"bytes,3,opt,name=old,proto3" json:"old,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kvstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeleteResponse) GetOld() []byte {
	if x != nil {
		return x.Old
	}
	return nil
}

// BatchPutRequest defines the request structure for BatchPut
type BatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         []*KeyValue            `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
	mi := &file_kvstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutRequest.ProtoReflect.Descriptor instead.
func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{6}
}

func (x *BatchPutRequest) GetPairs() []*KeyValue {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// BatchPutResponse defines the response structure for BatchPut
type BatchPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutResponse) Reset() {
	*x = BatchPutResponse{}
	mi := &file_kvstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutResponse) ProtoMessage() {}

func (x *BatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutResponse.ProtoReflect.Descriptor instead.
func (*BatchPutResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *BatchPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// KeyValue is a single key-value pair
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_kvstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{8}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// ScanRequest defines the request structure for Scan
// const (
//
//	CMP_GE = +3 // >=
//	CMP_GT = +2 // >
//	CMP_LT = -2 // <
//	CMP_LE = -3 // <=
//
// )
type Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	I64           int64                  `protobuf:"varint,2,opt,name=i64,proto3" json:"i64,omitempty"`
	Str           []byte                 `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_kvstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *Value) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Value) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Value) GetStr() []byte {
	if x != nil {
		return x.Str
	}
	return nil
}

// 表达一行记录（包括列名和值）
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          []string               `protobuf:"bytes,1,rep,name=cols,proto3" json:"cols,omitempty"`
	Vals          []*Value               `protobuf:"bytes,2,rep,name=vals,proto3" json:"vals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_kvstore_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{10}
}

func (x *Record) GetCols() []string {
	if x != nil {
		return x.Cols
	}
	return nil
}

func (x *Record) GetVals() []*Value {
	if x != nil {
		return x.Vals
	}
	return nil
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyStart      []byte                 `protobuf:"bytes,1,opt,name=keyStart,proto3" json:"keyStart,omitempty"` // 起始键
	KeyEnd        []byte                 `protobuf:"bytes,2,opt,name=keyEnd,proto3" json:"keyEnd,omitempty"`     // 结束键
	Cmp1          int64                  `protobuf:"varint,3,opt,name=cmp1,proto3" json:"cmp1,omitempty"`        // 比较符号1（>= 或 >）
	Cmp2          int64                  `protobuf:"varint,4,opt,name=cmp2,proto3" json:"cmp2,omitempty"`        // 比较符号2（<= 或 <）
	Table         []byte                 `protobuf:"bytes,5,opt,name=table,proto3" json:"table,omitempty"`
	Index         int64                  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_kvstore_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{11}
}

func (x *ScanRequest) GetKeyStart() []byte {
	if x != nil {
		return x.KeyStart
	}
	return nil
}

func (x *ScanRequest) GetKeyEnd() []byte {
	if x != nil {
		return x.KeyEnd
	}
	return nil
}

func (x *ScanRequest) GetCmp1() int64 {
	if x != nil {
		return x.Cmp1
	}
	return 0
}

func (x *ScanRequest) GetCmp2() int64 {
	if x != nil {
		return x.Cmp2
	}
	return 0
}

func (x *ScanRequest) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *ScanRequest) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

// ScanResponse defines the response structure for Scan
type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_kvstore_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{12}
}

func (x *ScanResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// StatusRequest defines the request structure for Status
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_kvstore_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{13}
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Grpcaddress   string                 `protobuf:"bytes,3,opt,name=grpcaddress,proto3" json:"grpcaddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_kvstore_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{14}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Node) GetGrpcaddress() string {
	if x != nil {
		return x.Grpcaddress
	}
	return ""
}

// StatusResponse defines the response structure for Status
type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Me            *Node                  `protobuf:"bytes,1,opt,name=me,proto3" json:"me,omitempty"`
	Leader        *Node                  `protobuf:"bytes,2,opt,name=leader,proto3" json:"leader,omitempty"`
	Follower      []*Node                `protobuf:"bytes,3,rep,name=follower,proto3" json:"follower,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kvstore_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{15}
}

func (x *StatusResponse) GetMe() *Node {
	if x != nil {
		return x.Me
	}
	return nil
}

func (x *StatusResponse) GetLeader() *Node {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *StatusResponse) GetFollower() []*Node {
	if x != nil {
		return x.Follower
	}
	return nil
}

// JoinRequest defines the request structure for Join
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // address of the new node to join the cluster
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_kvstore_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{16}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// JoinResponse defines the response structure for Join
type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_kvstore_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{17}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OperationType          `protobuf:"varint,1,opt,name=type,proto3,enum=OperationType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_kvstore_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_kvstore_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_kvstore_proto_rawDescGZIP(), []int{18}
}

func (x *Operation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_PUT
}

func (x *Operation) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Operation) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Operation) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_kvstore_proto protoreflect.FileDescriptor

const file_kvstore_proto_rawDesc = "" +
	"\n" +
	"\rkvstore.proto\"H\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\"i\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\bR\aupdated\x12\x14\n" +
	"\x05added\x18\x03 \x01(\bR\x05added\x12\x10\n" +
	"\x03old\x18\x04 \x01(\fR\x03old\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"R\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x10\n" +
	"\x03old\x18\x03 \x01(\fR\x03old\"2\n" +
	"\x0fBatchPutRequest\x12\x1f\n" +
	"\x05pairs\x18\x01 \x03(\v2\t.KeyValueR\x05pairs\",\n" +
	"\x10BatchPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"?\n" +
	"\x05Value\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x10\n" +
	"\x03i64\x18\x02 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03str\x18\x03 \x01(\fR\x03str\"8\n" +
	"\x06Record\x12\x12\n" +
	"\x04cols\x18\x01 \x03(\tR\x04cols\x12\x1a\n" +
	"\x04vals\x18\x02 \x03(\v2\x06.ValueR\x04vals\"\x95\x01\n" +
	"\vScanRequest\x12\x1a\n" +
	"\bkeyStart\x18\x01 \x01(\fR\bkeyStart\x12\x16\n" +
	"\x06keyEnd\x18\x02 \x01(\fR\x06keyEnd\x12\x12\n" +
	"\x04cmp1\x18\x03 \x01(\x03R\x04cmp1\x12\x12\n" +
	"\x04cmp2\x18\x04 \x01(\x03R\x04cmp2\x12\x14\n" +
	"\x05table\x18\x05 \x01(\fR\x05table\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x03R\x05index\"1\n" +
	"\fScanResponse\x12!\n" +
	"\arecords\x18\x01 \x03(\v2\a.RecordR\arecords\"\x0f\n" +
	"\rStatusRequest\"R\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12 \n" +
	"\vgrpcaddress\x18\x03 \x01(\tR\vgrpcaddress\"i\n" +
	"\x0eStatusResponse\x12\x15\n" +
	"\x02me\x18\x01 \x01(\v2\x05.NodeR\x02me\x12\x1d\n" +
	"\x06leader\x18\x02 \x01(\v2\x05.NodeR\x06leader\x12!\n" +
	"\bfollower\x18\x03 \x03(\v2\x05.NodeR\bfollower\"@\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"(\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\tOperation\x12\"\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0e.OperationTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x04R\x05index*E\n" +
	"\rOperationType\x12\a\n" +
	"\x03PUT\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\f\n" +
	"\bBATCHPUT\x10\x04\x12\b\n" +
	"\x04SCAN\x10\x052\x9e\x02\n" +
	"\aKVStore\x12 \n" +
	"\x03Put\x12\v.PutRequest\x1a\f.PutResponse\x12 \n" +
	"\x03Get\x12\v.GetRequest\x1a\f.GetResponse\x12)\n" +
	"\x06Delete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\x12/\n" +
	"\bBatchPut\x12\x10.BatchPutRequest\x1a\x11.BatchPutResponse\x12#\n" +
	"\x04Scan\x12\f.ScanRequest\x1a\r.ScanResponse\x12)\n" +
	"\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\x12#\n" +
	"\x04Join\x12\f.JoinRequest\x1a\r.JoinResponseB\x12Z\x10../raftpb;raftpbb\x06proto3"

var (
	file_kvstore_proto_rawDescOnce sync.Once
	file_kvstore_proto_rawDescData []byte
)

func file_kvstore_proto_rawDescGZIP() []byte {
	file_kvstore_proto_rawDescOnce.Do(func() {
		file_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvstore_proto_rawDesc), len(file_kvstore_proto_rawDesc)))
	})
	return file_kvstore_proto_rawDescData
}

var file_kvstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_kvstore_proto_goTypes = []any{
	(OperationType)(0),       // 0: OperationType
	(*PutRequest)(nil),       // 1: PutRequest
	(*PutResponse)(nil),      // 2: PutResponse
	(*GetRequest)(nil),       // 3: GetRequest
	(*GetResponse)(nil),      // 4: GetResponse
	(*DeleteRequest)(nil),    // 5: DeleteRequest
	(*DeleteResponse)(nil),   // 6: DeleteResponse
	(*BatchPutRequest)(nil),  // 7: BatchPutRequest
	(*BatchPutResponse)(nil), // 8: BatchPutResponse
	(*KeyValue)(nil),         // 9: KeyValue
	(*Value)(nil),            // 10: Value
	(*Record)(nil),           // 11: Record
	(*ScanRequest)(nil),      // 12: ScanRequest
	(*ScanResponse)(nil),     // 13: ScanResponse
	(*StatusRequest)(nil),    // 14: StatusRequest
	(*Node)(nil),             // 15: Node
	(*StatusResponse)(nil),   // 16: StatusResponse
	(*JoinRequest)(nil),      // 17: JoinRequest
	(*JoinResponse)(nil),     // 18: JoinResponse
	(*Operation)(nil),        // 19: Operation
}
var file_kvstore_proto_depIdxs = []int32{
	9,  // 0: BatchPutRequest.pairs:type_name -> KeyValue
	10, // 1: Record.vals:type_name -> Value
	11, // 2: ScanResponse.records:type_name -> Record
	15, // 3: StatusResponse.me:type_name -> Node
	15, // 4: StatusResponse.leader:type_name -> Node
	15, // 5: StatusResponse.follower:type_name -> Node
	0,  // 6: Operation.type:type_name -> OperationType
	1,  // 7: KVStore.Put:input_type -> PutRequest
	3,  // 8: KVStore.Get:input_type -> GetRequest
	5,  // 9: KVStore.Delete:input_type -> DeleteRequest
	7,  // 10: KVStore.BatchPut:input_type -> BatchPutRequest
	12, // 11: KVStore.Scan:input_type -> ScanRequest
	14, // 12: KVStore.Status:input_type -> StatusRequest
	17, // 13: KVStore.Join:input_type -> JoinRequest
	2,  // 14: KVStore.Put:output_type -> PutResponse
	4,  // 15: KVStore.Get:output_type -> GetResponse
	6,  // 16: KVStore.Delete:output_type -> DeleteResponse
	8,  // 17: KVStore.BatchPut:output_type -> BatchPutResponse
	13, // 18: KVStore.Scan:output_type -> ScanResponse
	16, // 19: KVStore.Status:output_type -> StatusResponse
	18, // 20: KVStore.Join:output_type -> JoinResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_kvstore_proto_init() }
func file_kvstore_proto_init() {
	if File_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvstore_proto_rawDesc), len(file_kvstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvstore_proto_goTypes,
		DependencyIndexes: file_kvstore_proto_depIdxs,
		EnumInfos:         file_kvstore_proto_enumTypes,
		MessageInfos:      file_kvstore_proto_msgTypes,
	}.Build()
	File_kvstore_proto = out.File
	file_kvstore_proto_goTypes = nil
	file_kvstore_proto_depIdxs = nil
}
